name: test-of-action

on:
  push:

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: verify if rebased
        uses: informeai/verify-if-rebased
        with:
          gh-token: ${{ env.GH_TOKEN }} 